# Generated by Django 6.1 on 2026-09-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="resource_type",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
