# Generated by Django 6.1 on 2026-09-05 15:58
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0002_bookmark_resource_type"),
    ]

    operations = [
        TrigramExtension(),
    ]
