# Generated by Django 6.1 on 2026-09-05 16:00

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0003_enable_pg_trgm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bookmark",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="title_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
